name = "johndope/darkluagametemplate"
version = "0.1.0"
description = "john dope"
authors = ["john dope"]
repository = "https://github.com/JonhDope/darklua-game-template.git"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
darklua = { name = "pesde/darklua", version = "^0.17.1", target = "lune" }
